import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Jazz Abad",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  products: [
    {
      //_id: "1",
      name: "Alexa Smart Speaker",
      slug: "alexa-smart-speaker",
      category: "Electronics",
      image: "/images/alexa.jpg",
      price: 99,
      countInStock: 5,
      brand: "Amazon",
      rating: 4.2,
      numReviews: 8,
      description: "Voice-controlled smart speaker",
      isActive: true,
    },
    {
      //_id: "2",
      name: "Apple AirPods",
      slug: "apple-airpods",
      category: "Electronics",
      image: "/images/airpods.jpg",
      price: 159,
      countInStock: 15,
      brand: "Apple",
      rating: 4.8,
      numReviews: 20,
      description: "Wireless earbuds with charging case",
      isActive: true,
    },
    {
      //_id: "3",
      name: "Canon EOS Rebel T7 Camera",
      slug: "canon-eos-rebel-t7-camera",
      category: "Cameras",
      image: "/images/camera.jpg",
      price: 499,
      countInStock: 7,
      brand: "Canon",
      rating: 4.5,
      numReviews: 15,
      description: "24.1 Megapixel CMOS Sensor Digital Camera",
      isActive: true,
    },

    {
      //_id: "4",
      name: "Logitech Wireless Mouse",
      slug: "logitech-wireless-mouse",
      category: "Accessories",
      image: "/images/mouse.jpg",
      price: 25,
      countInStock: 20,
      brand: "Logitech",
      rating: 4.1,
      numReviews: 7,
      description: "Wireless mouse with long battery life",
      isActive: true,
    },

    {
      //_id: "5",
      name: "PlayStation 5",
      slug: "playstation-5",
      category: "Gaming",
      image: "/images/playstation.jpg",
      price: 499,
      countInStock: 3,
      brand: "Sony",
      rating: 4.9,
      numReviews: 25,
      description: "The latest gaming console from Sony",
      isActive: true,
    },

    {
      //_id: "6",
      name: "iPhone 13",
      slug: "iphone-13",
      category: "Phones",
      image: "/images/phone.jpg",
      price: 999,
      countInStock: 12,
      brand: "Apple",
      rating: 4.7,
      numReviews: 18,
      description: "The latest iPhone with new features",
      isActive: true,
    },
  ],
};

export default data;
