const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Shirts",
    },
    {
      name: "Addidas Fit Shirt",
      slug: "addidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Shirts",
    },
    {
      name: "Nike Slim Pants",
      slug: "nike-slim-Pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Pants",
    },
    {
      name: "Addidas Fit Pants",
      slug: "addidas-fit-Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Pants",
    },
  ],
};

export default data;
